version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    environment:
      - AWS_REGION=ap-south-1
      - S3_BUCKET=protectdocs
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
